name: deforestation_2
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  
  # Core scientific packages
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  
  # Geospatial
  - rasterio
  - rioxarray
  
  # Pip packages
  - pip:
      - tensorflow==2.15.0
      - keras==2.15.0
      - segmentation-models==1.0.1
      - pyunpack==0.3
      - patool==4.0.2
      - rarfile==4.2